### PR TITLE
Update README.md to tell the truth

### PR DESCRIPTION
**Pull request by rubinovitz**

### CODE REVIEW

**Comment by rubinovitz** [comment]
address issue #4  and other transparency issues

**Comment by AbdouSarr** [comment]
This is just childish. He already issued an apology, be the bigger person.

**Comment by nsgomez** [comment]
@AbdouSarr The apology wasn't really an apology and I think we're worse off now than we were before. That's not to say this PR is productive though.

**Comment by rubinovitz** [comment]
Yeah, not helpful. What is done is done. Closing.

**Pull request closed without merging**
