### PR TITLE
Delete my work

### PR DESCRIPTION
**Pull request by rubinovitz**
Please delete my work from this repo I started and am now denied access to.

### CODE REVIEW

**Comment by nsgomez** [comment]
Just delete the whole repo ¯\_(ツ)_/¯

**Comment by rubinovitz** [comment]
Or please change sidebar link to http://hh.gd/org instead of using my work without my consent.

**Comment by nsgomez** [comment]
@rubinovitz I don't think any other admins are going to be notified without tagging them since you're the only one who contributed to this repo.

**Comment by rubinovitz** [comment]
@hellyeah ^

**Pull request merged**
